/*
 * Copyright 2016 Netbeans Liberty Plugin.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.netbeans.modules.liberty.main;

import java.io.File;

/**
 * Pop-up to choose the Liberty installation directory.
 *
 * @author sknitelius
 */
public class LibertyInstanceLocationChooser extends javax.swing.JDialog {

    private LibertyInstanceManagerPanel managerPanel;

    /**
     * Creates new form LibertyInstanceLocationChooser
     */
    public LibertyInstanceLocationChooser(java.awt.Frame parent, boolean modal, LibertyInstance serverInfo) {
        super(parent, modal);
        this.serverInfo1 = serverInfo;
        initComponents();
        setAlwaysOnTop(true);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

    serverInfo1 = new org.netbeans.modules.liberty.main.LibertyInstance();
    libertyLocationChoser = new javax.swing.JFileChooser();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    libertyLocationChoser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

    org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, serverInfo1, org.jdesktop.beansbinding.ELProperty.create("${runtimeLocation}"), libertyLocationChoser, org.jdesktop.beansbinding.BeanProperty.create("selectedFile"));
    bindingGroup.addBinding(binding);

    libertyLocationChoser.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        libertyLocationChoserActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(libertyLocationChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(libertyLocationChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    bindingGroup.bind();

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void libertyLocationChoserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libertyLocationChoserActionPerformed
        final File selectedFile = libertyLocationChoser.getSelectedFile();
        managerPanel.setLibertyLocation(selectedFile.getAbsolutePath());
    }//GEN-LAST:event_libertyLocationChoserActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JFileChooser libertyLocationChoser;
  private org.netbeans.modules.liberty.main.LibertyInstance serverInfo1;
  private org.jdesktop.beansbinding.BindingGroup bindingGroup;
  // End of variables declaration//GEN-END:variables

    public void setManagerPanel(LibertyInstanceManagerPanel managerPanel) {
        this.managerPanel = managerPanel;
    }
}
