/*
 * Popup to chose the location of the Liberty Instance.
 */
package org.netbeans.modules.liberty.main;

import java.io.File;

/**
 * Pop-up to choose the Liberty installation directory.
 *
 * @author sknitelius
 */
public class LibertyInstanceLocationChooser extends javax.swing.JDialog {

  private LibertyInstanceManagerPanel managerPanel;

  /**
   * Creates new form LibertyInstanceLocationChooser
   */
  public LibertyInstanceLocationChooser(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    setAlwaysOnTop(true);
    setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    libertyLocationChoser = new javax.swing.JFileChooser();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    libertyLocationChoser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
    libertyLocationChoser.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        libertyLocationChoserActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(libertyLocationChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(libertyLocationChoser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void libertyLocationChoserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libertyLocationChoserActionPerformed
      final File selectedFile = libertyLocationChoser.getSelectedFile();
      managerPanel.setLibertyLocation(selectedFile.getAbsolutePath());
    }//GEN-LAST:event_libertyLocationChoserActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JFileChooser libertyLocationChoser;
  // End of variables declaration//GEN-END:variables

  public void setManagerPanel(LibertyInstanceManagerPanel managerPanel) {
    this.managerPanel = managerPanel;
  }
}
